services:
  - type: web
    name: dsavisualizer-backend
    env: java
    plan: free
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_VERSION
        value: 17