spring:
  application:
    name: dsa-backend
  
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    
  jackson:
    property-naming-strategy: SNAKE_CASE
    
server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: ${JWT_SECRET:defaultSecretKeyForDevelopmentOnlyChangeInProduction}
  expiration: 86400000 # 24 hours in milliseconds

cors:
  allowed-origins: 
    - http://localhost:5000
    - https://*.replit.app
    - https://*.replit.dev
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers:
    - "*"
  allow-credentials: true

logging:
  level:
    com.dsavisualizer: DEBUG
    org.springframework.security: DEBUG