-- Baseline for the schema that existed before Flyway was introduced.
-- IF NOT EXISTS keeps the first production run safe for databases previously
-- managed by Hibernate ddl-auto=update. It also makes a new database complete
-- enough for Hibernate validate before V2 adds the learning-loop tables.

CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(255) NOT NULL PRIMARY KEY,
    email VARCHAR(255) UNIQUE,
    password VARCHAR(255) NOT NULL,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    profile_image_url VARCHAR(255),
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS practice_problems (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    difficulty VARCHAR(255) NOT NULL,
    topic_id VARCHAR(255) NOT NULL,
    test_cases JSONB,
    solutions JSONB,
    time_complexity JSONB,
    space_complexity JSONB,
    solution TEXT,
    examples JSONB,
    test_set_version VARCHAR(255),
    boiler_plate_code TEXT,
    method_name VARCHAR(255),
    method_signature JSONB,
    created_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255),
    topic_id VARCHAR(255) NOT NULL,
    completed BOOLEAN,
    score INTEGER,
    time_spent INTEGER,
    completed_at TIMESTAMP,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_user_progress_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS user_solutions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255),
    problem_id BIGINT,
    code TEXT,
    language VARCHAR(255) NOT NULL,
    passed BOOLEAN,
    submitted_at TIMESTAMP,
    runtime DOUBLE PRECISION,
    memory INTEGER,
    CONSTRAINT fk_user_solutions_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_user_solutions_problem FOREIGN KEY (problem_id) REFERENCES practice_problems(id)
);

CREATE TABLE IF NOT EXISTS verification_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(255),
    user_id VARCHAR(255) NOT NULL,
    expiry_date TIMESTAMP,
    used BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_verification_tokens_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS forgot_password (
    fpid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    otp INTEGER NOT NULL,
    expiration_time TIMESTAMP NOT NULL,
    otp_consumed BOOLEAN,
    otp_verified_at TIMESTAMP,
    reset_proof_hash VARCHAR(128),
    reset_proof_purpose VARCHAR(64),
    reset_proof_expiration_time TIMESTAMP,
    reset_proof_consumed BOOLEAN,
    request_count INTEGER,
    request_window_started_at TIMESTAMP,
    user_id VARCHAR(255),
    CONSTRAINT fk_forgot_password_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS execution_receipts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id_hash VARCHAR(64) NOT NULL UNIQUE,
    user_id VARCHAR(255) NOT NULL,
    problem_id BIGINT NOT NULL,
    code_hash VARCHAR(64) NOT NULL,
    language VARCHAR(20) NOT NULL,
    test_set_version VARCHAR(64) NOT NULL,
    result VARCHAR(32) NOT NULL,
    issued_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    consumed_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_execution_receipts_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_execution_receipts_problem FOREIGN KEY (problem_id) REFERENCES practice_problems(id)
);

CREATE INDEX IF NOT EXISTS ix_execution_receipt_consume
    ON execution_receipts (user_id, problem_id, consumed_at);
