CREATE TABLE IF NOT EXISTS user_problem_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    problem_id BIGINT NOT NULL,
    draft_code TEXT,
    draft_language VARCHAR(32),
    time_spent_seconds INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'NOT_STARTED',
    best_runtime DOUBLE PRECISION,
    best_result_status VARCHAR(32),
    best_language VARCHAR(32),
    best_code_hash VARCHAR(64),
    last_execution_receipt_id BIGINT,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    completed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ux_user_problem_progress_user_problem UNIQUE (user_id, problem_id),
    CONSTRAINT fk_user_problem_progress_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_problem_progress_problem FOREIGN KEY (problem_id) REFERENCES practice_problems(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_problem_progress_receipt FOREIGN KEY (last_execution_receipt_id) REFERENCES execution_receipts(id)
);

CREATE INDEX IF NOT EXISTS ix_user_problem_progress_user_updated
    ON user_problem_progress (user_id, updated_at);
CREATE INDEX IF NOT EXISTS ix_user_problem_progress_problem
    ON user_problem_progress (problem_id);
CREATE INDEX IF NOT EXISTS ix_user_problem_progress_user_completed
    ON user_problem_progress (user_id, completed);

CREATE TABLE IF NOT EXISTS problem_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    problem_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    result_status VARCHAR(32),
    language VARCHAR(32) NOT NULL,
    code_hash VARCHAR(64),
    runtime DOUBLE PRECISION,
    memory INTEGER,
    execution_receipt_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_problem_attempts_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_problem_attempts_problem FOREIGN KEY (problem_id) REFERENCES practice_problems(id) ON DELETE CASCADE,
    CONSTRAINT fk_problem_attempts_receipt FOREIGN KEY (execution_receipt_id) REFERENCES execution_receipts(id)
);

CREATE INDEX IF NOT EXISTS ix_problem_attempts_user_problem_created
    ON problem_attempts (user_id, problem_id, created_at);
CREATE INDEX IF NOT EXISTS ix_problem_attempts_user_created
    ON problem_attempts (user_id, created_at);
CREATE INDEX IF NOT EXISTS ix_problem_attempts_receipt
    ON problem_attempts (execution_receipt_id);
